# Random Forest model

In [135]:
import pickle

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np


data_dict = pickle.load(open('./data.pickle', 'rb'))
# print(data_dict)
data = np.asarray(data_dict['data'])
labels = np.asarray(data_dict['labels'])
print(data)
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)
print(x_train)
model = RandomForestClassifier()

model.fit(x_train, y_train)

y_predict = model.predict(x_test)

score = accuracy_score(y_predict, y_test)

print('{}% of samples were classified correctly !'.format(score * 100))

f = open('model.p', 'wb')
pickle.dump({'model': model}, f)
f.close()

[[0.11496747 0.3724269  0.17920008 ... 0.19974169 0.0278025  0.21249658]
 [0.11542317 0.37056488 0.1794669  ... 0.20233339 0.02916023 0.21405879]
 [0.08891004 0.31196141 0.15014929 ... 0.1626997  0.02267814 0.17511496]
 ...
 [0.35218839 0.36828285 0.33648826 ... 0.06512567 0.         0.        ]
 [0.36460455 0.37728298 0.34933327 ... 0.06932023 0.         0.        ]
 [0.37413737 0.3874121  0.35646778 ... 0.06999609 0.         0.        ]]


# SVM model 

In [2]:
import pickle
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

# Load data
data_dict = pickle.load(open('./data.pickle', 'rb'))

data = np.asarray(data_dict['data'])
labels = np.asarray(data_dict['labels'])

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, shuffle=True, stratify=labels)

# Initialize the SVM model with RBF kernel
model = SVC(kernel='rbf')

# Train the model
model.fit(x_train, y_train)

# Make predictions
y_predict = model.predict(x_test)

# Calculate the accuracy score
score = accuracy_score(y_predict, y_test)

# Output the accuracy
print('{}% of samples were classified correctly!'.format(score * 100))

# Save the model
f = open('model.p', 'wb')
pickle.dump({'model': model}, f)
f.close()


99.65116279069768% of samples were classified correctly!


##### After testing two models in real time for American Sign Language detection, we found that Support Vector Machine (SVM) outperformed the other model in separating similar classes, providing better accuracy and classification performance.

In [123]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9],[1,2]]

In [127]:
b = np.array(a,dtype="object")

In [129]:
b

array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9]), list([1, 2])],
      dtype=object)

In [113]:
c = [0.10107269883155823, 0.48110872507095337, 0.14697688817977905, 0.42422324419021606, 0.18253517150878906, 0.3326295018196106, 0.21715977787971497, 0.27349162101745605, 0.2574153542518616, 0.23606646060943604, 0.09167447686195374, 0.22251510620117188, 0.07779935002326965, 0.12202638387680054, 0.07317551970481873, 0.05464008450508118, 0.06745168566703796, 0.0, 0.053266316652297974, 0.23942047357559204, 0.1198824942111969, 0.18486380577087402, 0.1485230028629303, 0.26837122440338135, 0.1365499496459961, 0.3077317476272583, 0.023782432079315186, 0.2714395523071289, 0.0969131588935852, 0.23966604471206665, 0.11673790216445923, 0.3150351047515869, 0.09842857718467712, 0.3441023826599121, 0.0, 0.31636810302734375, 0.06295698881149292, 0.28725624084472656, 0.08448722958564758, 0.337613582611084, 0.0692966878414154, 0.3637758493423462]

In [115]:
len(c)

42